path:
    velocity_data_path: "dataset/velocity_model/"
    client_seismic_data_path: "dataset/seismic_data/2B/" # Make sure this path is correct
    gt_seismic_data_path: "dataset/seismic_data/5_sources/" # Make sure this path is correct
    model_path: "pretrained_model/model.pt"
    output_path: "experiment_result/"

federated:
    num_rounds: 600
    local_epochs: 5
    local_lr: 0.01

experiment:
    strategy: "FedAvgM"
    regularization: "Total_Variation" # Make sure correct
    reg_lambda: 0.3
    server_momentum: 0.9
    num_clients: 2 # Make sure correct
    scenario_flag: 2B # Make sure correct

resources:
    num_cpus_per_client: 1
    num_gpus_per_client: 0.5

diffusion:
    dim: 64
    dim_mults: [1, 2, 4, 8]
    flash_attn: False
    channels: 1
    image_size: 72
    timesteps: 1000
    sampling_timesteps: 250
    objective: "pred_noise"
    
forward:
    initial_sigma: 10
    n_grid: 70
    nt: 1000
    dx: 10
    nbc: 120
    dt: 1e-3
    f: 15
    sz: 10
    gz: 10
    ng: 70
    ns: 5
    sx: null
