path:
    velocity_data_path: "dataset/velocity_model/"
    client_seismic_data_path: "dataset/seismic_data/3A/" # Make sure this path is correct
    gt_seismic_data_path: "dataset/seismic_data/10_sources/" # Make sure this path is correct
    model_path: "pretrained_model/model.pt"
    output_path: "experiment_result/"

experiment:
    regularization: "Diffusion" # Make sure correct
    reg_lambda: 0.75
    scenario_flag: 3A # Make sure correct

diffusion:
    dim: 64
    dim_mults: [1, 2, 4, 8]
    flash_attn: False
    channels: 1
    image_size: 72
    timesteps: 1000
    sampling_timesteps: 250
    objective: "pred_noise"
    
forward:
    initial_sigma: 10
    n_grid: 70
    nt: 1000
    dx: 10
    nbc: 120
    dt: 1e-3
    f: 15
    sz: 10
    gz: 10
    ng: 70
    ns: 10 # Make sure correct
    sx: null
